streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/mytheme, user/themes/antimatter-open-publishing, user/themes/antimatter]
chromeless:
  enabled: false
display_of_git_sync_repo_link: menu
type_of_git_sync_repo_link: view
method_for_git_sync: gitsyncplugin
displaypostsummary:
  enabled: false
cc_license:
  enabled: false
  type: ccby
displaycustommenus:
  enabled: false
hidehomemenulink: false
menu:
  -
    text: Grav
    icon: grav
    url: 'http://getgrav.org'
    target: _blank
header:
  post_icon: calendar-o
post_icon: newspaper-o
